project: 
  type: website

website:
  title: "Wedding of Christopher Martin Mikkelsen Cox and Johanne Sofie Krog Nedergård"

format:
  html:
    theme: [lux, theme.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto

  
