project: 
  type: website

website: 
  page-navigation: true
  title: "Wedding of Christopher Martin Mikkelsen Cox and Johanne Sofie Krog Nedergård"
  site-url: "https://4ccoxau.github.io/CoxAndNedergaardSayIDo/" 
  repo-url: "https://4ccoxau.github.io/CoxAndNedergaardSayIDo/"
  repo-actions: none
  favicon: images/favicon.png
  
  page-footer:
    right: ""
    left: ""

format:
  html:
    theme:
      light: [lux, theme.scss] 
      dark: [lux, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto

  
